INSERT INTO users (name, age) VALUES ("Harry", 25);
INSERT INTO users (name, age) VALUES ("Sally", 52);
INSERT INTO users (name, age) VALUES ("Joey", 37);
INSERT INTO users (name, age) VALUES ("Bob", 42);
INSERT INTO users (name, age) VALUES ("Mary", 22);
INSERT INTO users (name, age) VALUES ("Sharon", 19);
INSERT INTO users (name, age) VALUES ("Jake", 75);
INSERT INTO users (name, age) VALUES ("Jeff", 34);
INSERT INTO users (name, age) VALUES ("Elizabeth", 48);
INSERT INTO users (name, age) VALUES ("Annie", 39);
INSERT INTO users (name, age) VALUES ("John", 29);
INSERT INTO users (name, age) VALUES ("Nadine", 32);
INSERT INTO users (name, age) VALUES ("Shakira", 36);
INSERT INTO users (name, age) VALUES ("Evan", 18);
INSERT INTO users (name, age) VALUES ("David", 19);
INSERT INTO users (name, age) VALUES ("Cristina", 24);
INSERT INTO users (name, age) VALUES ("Tanya", 44);
INSERT INTO users (name, age) VALUES ("Phil", 61);
INSERT INTO users (name, age) VALUES ("Mike", 39);
INSERT INTO users (name, age) VALUES ("Amy", 63);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Heal the World", "Art", 1000, 2020-03-21, 2020-03-27);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("COVID Map", "Public Health", 5000, 2020-03-24, 2020-03-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Real Love", "Music", 17000, 2020-02-01, 2020-04-21);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Kid A", "Music", 2000, 2020-03-15, 2020-03-30);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Mona Lisa", "Art", 500, 2020-01-21, 2020-03-24);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ventilator Production", "Public Health", 10000, 2020-03-15, 2020-05-01);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Virus Testers", "Public Health", 700, 2020-03-10, 2020-04-17);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sudoku Chess", "Games", 3500, 2020-03-13, 2020-04-13);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pandemic With Friends", "Games", 7500, 2020-03-25, 2020-04-25);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("The David", "Art", 100000, 2019-12-25, 2020-03-15);

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 11, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 14, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 15, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 16, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 17, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 19, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 20, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 2, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 6, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 7, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 8, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);